# Configuration specific to Sonarr
sonarr:
    # Sonarr
  - base_url: http://192.168.5.150:8989
    api_key: *****

    # Quality definitions from the guide to sync to Sonarr. Choice: anime, series, hybrid
    quality_definition: series

    # Release profiles from the guide to sync to Sonarr. Types: anime, series
    # You can optionally add tags and make negative scores strictly ignored
    release_profiles:
      - trash_ids:
        - EBC725268D687D588A20CBC5F97E538B # Low Quality Groups
        - 1B018E0C53EC825085DD911102E2CA36 # Release Sources (Streaming Service)
        - 71899E6C303A07AF0E4746EFF9873532 # P2P Groups + Repack/Proper
        strict_negative_scores: false
      - trash_ids: [76e060895c5b8a765c310933da0a5357] # Optionals
        filter:
          include:
            - cec8880b847dd5d31d29167ee0112b57 # Golden Rule - No x265
            - 6f2aefa61342a63387f2a90489e90790 # Dislike Retags
            - 19cd5ecc0a24bf493a75e80a51974cdd # Dislike Retag Groups

# Configuration specific to Radarr.
radarr:
  # Radarr
  - base_url: http://192.168.5.150:7878
    api_key: *****

    # Which quality definition in the guide to sync to Radarr. Only choice right now is 'movie'
    quality_definition:
      type: movie
      preferred_ratio: 0.5

    # Set to 'true' to automatically remove custom formats from Radarr when they are removed from
    # the guide or your configuration. This will NEVER delete custom formats you manually created!
    delete_old_custom_formats: true

    custom_formats:
      # A list of custom formats to sync to Radarr. Must match the "name" in the importable JSON.
      # Do NOT use the heading names here, those do not work! These are case-insensitive.
      - names:
          # Unwanted
          - BR-DISK
          - EVO (no WEBDL)
          - LQ
          - x265 (720/1080p)
          - 3D
          - No-RlsGroup
          - Obfuscated
          - DV (WEBDL)
          # Wanted
          - TrueHD ATMOS
          - DTS X
          - ATMOS (undefined)
          - DD+ ATMOS
          - TrueHD
          - DTS-HD MA
          - FLAC
          - PCM
          - DTS-HD HRA
          - DD+
          - DTS-ES
          - DTS
          - AAC
          - DD
          - Hybrid
          - Remaster
          - 4K Remaster
          - Criterion Collection
          - Special Edition
          - IMAX
          - IMAX Enhanced
          - Repack/Proper
          - HQ
          - HQ-WEBDL
          - HQ-Remux
        quality_profiles:
          - name: 1080p


    #Radarr4k
  - base_url: http://192.168.5.150:7879
    api_key: *****

    # Which quality definition in the guide to sync to Radarr. Only choice right now is 'movie'
    quality_definition:
      type: movie
      preferred_ratio: 0.5

    # Set to 'true' to automatically remove custom formats from Radarr when they are removed from
    # the guide or your configuration. This will NEVER delete custom formats you manually created!
    delete_old_custom_formats: true

    custom_formats:
      # A list of custom formats to sync to Radarr. Must match the "name" in the importable JSON.
      # Do NOT use the heading names here, those do not work! These are case-insensitive.
      - names:
          # Unwanted
          - BR-DISK
          - EVO (no WEBDL)
          - LQ
          - 3D
          - No-RlsGroup
          - Obfuscated
          - DV (WEBDL)
          # Wanted
          - TrueHD ATMOS
          - DTS X
          - ATMOS (undefined)
          - DD+ ATMOS
          - TrueHD
          - DTS-HD MA
          - FLAC
          - PCM
          - DTS-HD HRA
          - DD+
          - DTS-ES
          - DTS
          - AAC
          - DD
          - Hybrid
          - Remaster
          - 4K Remaster
          - Criterion Collection
          - Special Edition
          - IMAX
          - IMAX Enhanced
          - Repack/Proper
          - HQ
          - HQ-WEBDL
          - HQ-Remux
          - DV HDR10
          - DV
          - DV HLG
          - DV SDR
          - HDR10+
          - HDR10
          - HDR
          - HDR (undefined)
          - PQ
          - HLG
        quality_profiles:
          - name: 4K
